### ISSUE TITLE
Being applied to svg's added via the wysiwyg

### ISSUE THREAD

**Issue by thisislawatts** [kylereicks/picturefill.js.wp#48]
Even though WordPress doesn't officially support SVG, if people are dabbling with resolution orientated images you could assume they may have some SVG love going on. So let's leave their images in touch

**Comment by tychay** [comment]
This is a good idea, you could also check to the content type, but picture fill currently biases the URL over the attachment data.

**Comment by kylereicks** [comment]
I have added a new filter "picturefill_wp_process_this_image" that has a default value of true, and that will be passed the image DOM node and post HTML data to reference.

To exclude svg:
```
add_filter('picturefill_wp_process_this_image', 'picturefill_wp_exclude_svg', 10, 3);

function picturefill_wp_exclude_svg($process, $image, $html){
    if(preg_match('/.svg$/i', $image->getAttribute('src'))){
    return false;
    }
    return $process;
}
```

**Comment by thisislawatts** [comment]
That's great @kylereicks, thanks for adding this into the plugin. Much tidier implementation as well to include it as a filter.
