### ISSUE TITLE
Incorrect image being loaded, and invalid sizes value being set

### ISSUE THREAD

**Issue by iandevlin** [kylereicks/picturefill.js.wp#59]
At the moment, on a site that I have (sadly, it's local only) the plugin is creating the following code:
```html
<img sizes="(max-width: 100%px) 100vw, 100%px" 
     srcset="img-150x150.png 150w, img-300x160.png 300w, img.png 1001w" 
	 height="100%" 
	 width="100%">
```
The image being loaded (original image is 1001x534), regardless of viewport width, is `img-150x150.png`, and, as you can see, the `sizes` media query is invalid, mixing both % and 'px'. I assume that this is causing the problem, although I am not sure how it is occurring.

I am currently using the plugin "as is", and haven't manually set any `srcset` nor `sizes` values.

**edit**
Ok, I have found out why this is occurring, in `class-model-image-picturefill-wp.php` in the `get_sizes_string` method, `$this->image_attributes['width']` has a percentage value, and therefore the HTML that is output is incorrect.

I have "fixed" (you will be the better judge of that!) this by doing the following:

Before returning the built HTML string, check if the value contained in `$this->image_attributes['width']` has a '%' in it, and if so, use `getimagesize` to retrieve the actual image's width and use that instead:

```php
$width = $this->image_attributes['width'];
if (strpos($width, '%') !== FALSE) {
   $parsed_data = parse_url($this->image_attributes['src']);
   $image_size = getimagesize($_SERVER['DOCUMENT_ROOT'] . $parsed_data['path']);
   $width = $image_size[0];
}

return '(max-width: ' . $width . 'px) 100vw, ' . $width . 'px';
```

Thoughts appreciated!

**Comment by tychay** [comment]
I have a strong suspicion that you have `<img … width="100%"… />` tags in your post content somewhere. Those are invalid tags, since the way you construct 100% images is <img … style="width:100%…" />

**Comment by iandevlin** [comment]
Yes, the width and height are set to 100%, but not by me, by an editor, which is of course possible and the plugin should deal with it. My fix above, solves the issue though.

I have given up on this plugin though, I initially failed to see that the author isn't supporting it anymore. Thanks for you comment nonetheless.
